UrbanArt/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auth.urls')),
    path('index/', include('main.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auth/urls.py
from django.urls import path

from auth import views

urlpatterns = [
    path('', views.Login.as_view(), name = 'home-page'),
    path('artistsignup', views.ArtistSignUp.as_view(), name = "aSignUp"),
    path('usersignup', views.UserSignUp.as_view(), name = "uSignUp"),
    path('logout', views.Logout.as_view(), name = 'logout'),
    path('delete-user/<int:pk>', views.DeleteUser.as_view(), name = 'delete-user'),
    path('delete-artist/<int:pk>', views.DeleteArtist.as_view(), name = 'delete-artist')
]

main/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from main import views

urlpatterns = [
    path('', views.Index.as_view(), name = 'paintings'),
    path('painting/<int:pk>', views.Painting.as_view(), name = 'view-painting'),
    path('profile/<int:pk>', views.ArtistProfile.as_view(), name = 'view-profile'),
    path('artists', views.Artists.as_view(), name = 'artists'),
    path('artists/<int:artist_id>/add-painting', views.AddPainting.as_view(), name = 'add-painting'),
    path('buy-painting/<int:user_id>/<int:artist_id>/<int:painting_id>/', views.Payment.as_view(), name = 'buy-painting'),
    path('thankyou/', views.Success.as_view()),
    path('current-user/', views.CurrentProfile, name = 'current-profile'),
    path('current-user/change-profile-picture/<int:pk>/', views.ChangeProfilePicture.as_view(), name = 'change-picture')
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Artist(models.Model):
    workEx = models.PositiveIntegerField()
    style = models.CharField(max_length = 256)
    medium = models.CharField(max_length = 256)
    photo = models.ImageField(upload_to = 'profile_image', blank = True, null = True)
    # ToDo: description in markdown

    def __str__(self):
        return self.profile.username

class Profile(User):
    contact = models.CharField(max_length = 15)
    address = models.CharField(max_length = 256)
    artist = models.OneToOneField('Artist', on_delete = models.CASCADE, null = True, blank = True)

class Painting(models.Model):
    name = models.CharField(max_length = 256)
    price = models.IntegerField()
    artist = models.ForeignKey('Artist', on_delete = models.CASCADE)
    medium = models.CharField(max_length = 256)
    style = models.CharField(max_length = 256)
    size = models.CharField(max_length = 256)
    photo = models.ImageField(upload_to = 'painting_image', blank = True, null = True)
    soldStatus = models.BooleanField(default = False)

    def __str__(self):
        return self.name

class Payment(models.Model):
    PAYMENT_OPTIONS = [
        ('cc', 'Credit Card'),
        ('dc', 'Debit Card')
    ]
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    painting = models.OneToOneField('Painting', on_delete = models.CASCADE)
    artist = models.ForeignKey('Artist', on_delete = models.CASCADE)
    mode = models.CharField(max_length = 256, choices = PAYMENT_OPTIONS)
    payment_time = models.DateTimeField(auto_now_add=True)
    card_number = models.CharField(max_length = 256)
    name_on_card = models.CharField(max_length = 256)
    expiration_month = models.IntegerField()
    expiration_year = models.IntegerField()
    cvv = models.IntegerField()

    def __str__(self):
        return "{} bought {} from {}".format(self.user.username, self.painting.name, self.artist.profile.username)

main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User

# Create your views here.

from main import models

class Index(ListView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        allArtists = models.Artist.objects.all()
        context['artists'] = allArtists
        return context

    model = models.Painting
    template_name = 'main/index.html'

class ChangeProfilePicture(UpdateView):
    model = models.Artist
    fields = ['photo']
    template_name = 'main/change-profile.html'
    
    def get_success_url(self):
        return '/index/current-user/'

    def form_valid(self, form):
        form.save()

        return HttpResponseRedirect(self.get_success_url())

class ArtistProfile(DetailView):
    model = models.Artist
    template_name = 'main/artist-profile.html'

class Artists(ListView):
    model = models.Artist
    template_name = 'main/artists.html'

class AddPainting(CreateView):
    model = models.Painting
    fields = [
        'name',
        'price',
        'medium',
        'style',
        'size',
        'photo'
    ]
    template_name = 'main/add-painting.html'

    def get_success_url(self):
        return '/index/current-user'

    def form_valid(self, form):
        artist = models.Artist.objects.get(id = self.kwargs['artist_id'])

        newPainting = form.save(commit=False)
        newPainting.artist = artist
        newPainting.save()

        return HttpResponseRedirect(self.get_success_url())

class Painting(DetailView):
    model = models.Painting
    template_name = 'main/painting.html'

class Payment(CreateView):
    template_name = 'main/payment.html'
    model = models.Payment

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['artist'] = models.Artist.objects.get(id = self.kwargs['artist_id'])
        context['painting'] = models.Painting.objects.get(id = self.kwargs['painting_id'])
        return context

    fields = [
        'mode',
        'card_number',
        'name_on_card',
        'expiration_month',
        'expiration_year',
        'cvv'
    ]

    def form_valid(self, form):
        artist = models.Artist.objects.get(id = self.kwargs['artist_id'])
        user = User.objects.get(id = self.kwargs['user_id'])
        painting = models.Painting.objects.get(id = self.kwargs['painting_id'])
        painting.soldStatus = True
        painting.save()
        paymentDetails = form.save(commit = False)

        paymentDetails.user = user
        paymentDetails.artist = artist
        paymentDetails.painting = painting

        paymentDetails.save()

        return HttpResponseRedirect('/index/thankyou')

class Success(TemplateView):
    template_name = 'main/success.html'

def CurrentProfile(request):
    try:
        user = models.Artist.objects.get(profile = request.user)
    except:
        user = models.Profile.objects.get(id = request.user.id)

    try:
        buyers = models.Payment.objects.filter(artist = models.Artist.objects.get(profile = request.user))
    except:
        buyers = None

    Context = {
        'user': user,
        'orders': models.Payment.objects.filter(user = request.user),
        'buyers': buyers
    }

    return render(request, 'main/current-user.html', Context)

templates/main/add-painting.html
{% extends 'main/layouts/base.html' %}

{% block content %}

<div class="container payment-container mt-5">


    <div class="card payment-card">
        <div class="card-header">
            Add a new masterpiece!
        </div>
        <div class="card-body">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="id_name">Name</label>
                        <input type="text" name="name" maxlength="256" required="" id="id_name" class="form-control"
                            placeholder="Name">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="id_price">Price</label>
                        <input type="number" name="price" required="" id="id_price" class="form-control"
                            placeholder="Price">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="id_medium">Medium</label>
                        <input type="text" name="medium" maxlength="256" required="" id="id_medium" class="form-control"
                            placeholder="Medium">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="id_style">Style</label>
                        <input type="text" name="style" maxlength="256" required="" id="id_style" class="form-control"
                            placeholder="Style">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="id_size">Size</label>
                        <input type="text" name="size" maxlength="256" required="" id="id_size" class="form-control"
                            placeholder="Size">
                    </div>
                    <div class="form-group col-md-6">
                        <div class="input-group-prepend">
                            <span id="inputGroupFileAddon01" class="mb-2">Photo</span>
                        </div>
                        <div class="custom-file">
                            <label class="custom-file-label" for="id_photo">Choose a painting</label><br>
                            <input type="file" class="custom-file-input" name="photo" accept="image/*" id="id_photo">
                        </div>
                        <!-- <label for="id_photo">Photo:</label><input type="file" name="photo" accept="image/*"
                            id="id_photo"> -->

                    </div>
                </div>
                <div class="row justify-content-center">
                    <button type="submit" class="btn btn-outline-danger">ADD</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/main/artist-profile.html
{% extends 'main/layouts/base.html' %}

{% load static %}

{% block content %}
<div class="container profile-container">
    <div class="profile-picture rounded-circle">
        <img src="{{ artist.photo.url }}" alt="">
    </div>

    <div class="row justify-content-center">
        <table class="table table-bordered">
            <tbody>
                <tr>
                    <th scope="row" class="text-right">Name</th>
                    <td>{{ artist.profile.first_name }} {{ artist.profile.last_name }}</td>
                </tr>
                <tr>
                    <th scope="row" class="text-right">Contact</th>
                    <td>{{ artist.profile.contact }}</td>
                </tr>
                <tr>
                    <th scope="row" class="text-right">E-mail</th>
                    <td colspan="2">{{ artist.profile.email }}</td>
                </tr>
                <tr>
                    <th scope="row" class="text-right">Medium</th>
                    <td colspan="2">{{ artist.medium }}</td>
                </tr>
                <tr>
                    <th scope="row" class="text-right">Style</th>
                    <td colspan="2">{{ artist.style }}</td>
                </tr>
                <tr>
                    <th scope="row" class="text-right">Experience</th>
                    <td colspan="2">{{ artist.workEx }} Years</td>
                </tr>
                <tr>
                    <th scope="row" class="text-right">Address</th>
                    <td colspan="2">{{ artist.profile.address }}</td>
                </tr>

            </tbody>
        </table>
    </div>

    <div class="painting-partition text-center">
        {{ artist.profile.first_name }} {{ artist.profile.last_name }}'s paintings
    </div>
    <div class="container-fluid">


        <div class="row">


            {% for painting in artist.painting_set.all %}
            <div class="col-4">
                <div class="card-group">
                    <div class="card painting-card">
                        <img class="card-img-top" src="{{ painting.photo.url }}" alt="Card image cap">
                        <div class="card-body">
                            <p class="card-text">
                                <div class="card-title">
                                    <h4>{{ painting.name }}</h4>
                                </div>
                                <h5>Style: {{ painting.style }}</h5>
                                <h5>Medium: {{ painting.medium }}</h5>
                                <h5>Price: {{ painting.price }}</h5>
                                <h5>Size: {{ painting.size }}</h5>
                            </p>
                            {% if painting.soldStatus is True  %}
                            <button class="btn btn-dark disabled">
                                Sold
                            </button>
                            {% elif painting.artist.profile.id is request.user.id  %}
                            <a>
                                <button class="btn btn-outline-danger disabled">
                                    Buy
                                </button>
                            </a>
                            {% else %}
                            <a href="{% url 'buy-painting' user.id painting.artist.id painting.id %}">
                                <button class="btn btn-outline-danger">
                                    Buy
                                </button>
                            </a>
                            {% endif %}
                            <a href="{% url 'view-painting' painting.id %}" class="btn btn-outline-danger ml-2">View
                                Painting</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/main/artists.html
{% extends 'main/layouts/base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        {% for artist in artist_list %}
        <div class="col-3">
            <div class="card-group">
                {% include 'main/components/artist-card.html' %}
            </div>
        </div>
        {% endfor%}
    </div>
</div>
{% endblock %}

templates/main/change-profile.html
{% extends 'main/layouts/base.html' %}

{% block content %}
<!-- <div class="container payment-container mt-5">
    <div class="card payment-card">
        <div class="card-header">
            Change progile picture
        </div>
        <div class="card-body">
            <p>Current</p>
                <img src="{{ artist.photo.url }}">
            <form method="POST">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group">
                        <p class="mb-2">Card</p>
                        <div class="input-group">
                            <select class="custom-select" name="mode" required="" id="id_mode">
                                <option value="" selected="">Select</option>
                                <option value="cc">Credit Card</option>
                                <option value="dc">Debit Card</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group ">
                        <label for="id_card_number">Card number</label><input type="text" name="card_number"
                            maxlength="256" required="" id="id_card_number" class="form-control"
                            placeholder="Card Number">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group ">
                        <label for="id_name_on_card">Name on card</label><input type="text" name="name_on_card"
                            maxlength="256" required="" id="id_name_on_card" class="form-control"
                            placeholder="Name on card">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group ">
                        <label for="id_expiration_month">Expiration month</label><input type="number"
                            name="expiration_month" required="" id="id_expiration_month" class="form-control"
                            placeholder="Expiration month">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group ">
                        <label for="id_expiration_year">Expiration year</label><input type="number"
                            name="expiration_year" required="" id="id_expiration_year" class="form-control"
                            placeholder="Expiration year">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group ">
                        <label for="id_cvv">CVV</label><input type="number" name="cvv" required="" id="id_cvv"
                            class="form-control" placeholder="CVV">
                    </div>
                </div>
                <div class="row justify-content-center">
                    <button type="submit" class="btn btn-outline-danger">Pay <i class="fas fa-rupee-sign ml-2"
                            style="font-size: 0.9rem;"></i> {{ painting.price }}</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="card mt-5" id="artistSignUpForm">
    <div class="card-header"><a href="/" id="arrow"><i class="fas fa-arrow-left"></i></a><span
            style="padding: 20px">Sign Up as an Artist</span></div>
    <div class="card-body">
        <form method="POST">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="id_first_name">First name</label>
                    <input type="text" name="first_name" maxlength="256" required="" id="id_first_name"
                        class="form-control" placeholder="First Name">
                </div>
                <div class="form-group col-md-6">
                    <label for="id_last_name">Last name</label>
                    <input type="text" name="last_name" maxlength="256" required="" id="id_last_name"
                        class="form-control" placeholder="Last Name">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="id_username">Username</label>
                    <input type="text" name="username" maxlength="150" required="" id="id_username" class="form-control"
                        placeholder="Username">
                </div>
                <div class="form-group col-md-6">
                    <label for="id_email">E-mail</label>
                    <input type="text" name="email" class="form-control" required="" id="id_email" class="form-control"
                        placeholder="E-mail">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="id_password1">Password</label>
                    <input type="password" name="password1" required="" id="id_password1" class="form-control"
                        placeholder="Your password must contain at least 8 characters">
                </div>
                <div class="form-group col-md-6">
                    <label for="id_password2">Confirm Password</label><input type="password" name="password2"
                        required="" id="id_password2" class="form-control"
                        placeholder="Enter the same password as before">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="id_contact">Contact</label><input type="text" name="contact" maxlength="15" required=""
                        id="id_contact" class="form-control" placeholder="Phone number">
                </div>
                <div class="form-group col-md-6">
                    <label for="id_workEx">Work Experience</label>
                    <input type="number" name="workEx" min="0" required="" id="id_workEx" class="form-control"
                        placeholder="Work Experience">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="id_style">Style</label>
                    <input type="text" name="style" maxlength="256" required="" id="id_style" class="form-control"
                        placeholder="Style">
                </div>
                <div class="form-group col-md-6">
                    <label for="id_medium">Medium</label>
                    <input type="text" name="medium" maxlength="256" required="" id="id_medium" class="form-control"
                        placeholder="Medium">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="id_address">Address</label>
                    <input type="text" name="address" maxlength="256" required="" id="id_address" class="form-control"
                        placeholder="Address">
                </div>
                <div class="form-group col-md-6">
                    <div class="input-group-prepend">
                        <span id="inputGroupFileAddon01" class="mb-2">Photo</span>
                    </div>
                    <div class="custom-file">
                        <label class="custom-file-label" for="id_photo">Choose a profile picture</label><br>
                        <input type="file" class="custom-file-input" name="photo" accept="image/*" id="id_photo">
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <button type="submit" class="btn btn-outline-danger">Sign Up</button>
            </div>
        </form>
    </div>
</div> -->

<div class="container payment-container mt-5">
    <div class="card payment-card">
        <div class="card-header">
            Change progile picture
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-6">
                    <div class="current-pic">
                        <img src="{{ artist.photo.url }}">
                    </div>
                </div>
                <div class="col-6">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="input-group-prepend">
                            <span class="mb-2">Change picture</span>
                        </div>
                        <div class="custom-file">
                            <label class="custom-file-label" for="id_photo">Choose a profile picture</label><br>
                            <input type="file" class="custom-file-input" name="photo" accept="image/*" id="id_photo">
                        </div>
                        <input type="submit" value="Update" class="btn btn-danger">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- <form method="POST" enctype="multipart/form-data">

    <input type="checkbox" name="photo-clear" id="photo-clear_id">
    <label for="photo-clear_id">Clear</label><br>
    Change:
    <input type="file" name="photo" accept="image/*" id="id_photo">
    <input type="submit" value="Update">
</form>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Update">
</form> -->
{% endblock %}

templates/main/components/artist-card.html
<div class="card artist-card">
    <div class="crop">
        <img class="card-img-top" src="{{ artist.photo.url }}" alt="Card image cap">
    </div>
    <div class="card-body">
        <p class="card-text">
            <div class="card-title"><h4>{{ artist.profile.first_name }} {{ artist.profile.last_name }}</h4></div>
            <h5>Style: {{ artist.style }}</h5>
            <h5>Medium: {{ artist.medium }}</h5>
        </p>
        <a href="{% url 'view-profile' artist.id %}" class="btn btn-outline-danger">View Profile</a>
    </div>
</div>

templates/main/components/painting-card.html
<div class="card rounded-0 painting">
    <img src="{{ painting.photo.url }}" class="card-img-top" alt="...">
    <div class="content">
        <h2>{{ painting.name }}</h2>
        <p style="font-size: 1.25rem">Artist: {{ painting.artist.profile.first_name }} {{ painting.artist.profile.last_name }}</p style="font-size: 1.25rem">
    </div>
    <div class="action-button">
        {% if painting.soldStatus is True  %}
        <button class="btn btn-dark disabled">
            Sold
        </button>
        {% elif painting.artist.profile.id is request.user.id  %}
        <a>
            <button class="btn btn-outline-light disabled">
                Buy
            </button>
        </a>
        {% else %}
        <a href="{% url 'buy-painting' user.id painting.artist.id painting.id %}">
            <button class="btn btn-outline-light">
                Buy
            </button>
        </a>
        {% endif %}
    </div>
    <div class="painting-button">
        <a href="{% url 'view-painting' painting.id %}">
            <button class="btn btn-outline-light">
                View Painting
            </button>
        </a>
    </div>
    <div class="profile-button">
        <a href="{% url 'view-profile' painting.artist.id %}">
            <button class="btn btn-outline-light">
                View artist profile
            </button>
        </a>
    </div>
</div>

templates/main/index.html
{% extends 'main/layouts/base.html' %}

{% load static %}

{% block content %}

    <div class="card-columns">
        {% for painting in painting_list %}
            {% include 'main/components/painting-card.html' %}
        {% endfor%}
    </div>

    {% for artist in artists %}
        {% if artist.profile.id == request.user.id %}
            <a href="{% url 'add-painting' artist.id %}">
                <button class="addPaintingBtn btn btn-dark rounded-circle" data-toggle="tooltip" data-placement="top" title="Add your own painting">
                    <i class="fas fa-plus"></i>
                </button>
            </a>
        {% endif %}
    {% endfor %}

{% endblock %}

templates/main/payment.html
{% extends 'main/layouts/base.html' %}

{% block content %}
<div class="container payment-container mt-5">
    <div class="card payment-card">
        <div class="card-header">
            Buy {{ painting.name }}
        </div>
        <div class="card-body">
            <div class="painting-wrapper">
                <img src="{{ painting.photo.url }}" alt="">
            </div>
            <div class="artist-wrapper rounded-circle">
                <img src="{{ artist.photo.url }}" alt="">
            </div>
            <form method="POST">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group">
                        <p class="mb-2">Card</p>
                        <div class="input-group">
                            <select class="custom-select" name="mode" required="" id="id_mode">
                                <option value="" selected="">Select</option>
                                <option value="cc">Credit Card</option>
                                <option value="dc">Debit Card</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group ">
                        <label for="id_card_number">Card number</label><input type="text" name="card_number"
                            maxlength="256" required="" id="id_card_number" class="form-control"
                            placeholder="Card Number">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group ">
                        <label for="id_name_on_card">Name on card</label><input type="text" name="name_on_card"
                            maxlength="256" required="" id="id_name_on_card" class="form-control"
                            placeholder="Name on card">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group ">
                        <label for="id_expiration_month">Expiration month</label><input type="number"
                            name="expiration_month" required="" id="id_expiration_month" class="form-control"
                            placeholder="Expiration month">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group ">
                        <label for="id_expiration_year">Expiration year</label><input type="number"
                            name="expiration_year" required="" id="id_expiration_year" class="form-control"
                            placeholder="Expiration year">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group ">
                        <label for="id_cvv">CVV</label><input type="number" name="cvv" required="" id="id_cvv"
                            class="form-control" placeholder="CVV">
                    </div>
                </div>
                <div class="row justify-content-center">
                    <button type="submit" class="btn btn-outline-danger">Pay <i class="fas fa-rupee-sign ml-2" style="font-size: 0.9rem;"></i>  {{ painting.price }}</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/main/success.html
{% extends 'main/layouts/success-layout.html' %}

{% block content %}
<div class="jumbotron mt-5">
    <h1 class="display-4">Thank You for shopping with Urban Art!</h1>
    <hr class="my-4" style="width: 50%; left: -24%; position: relative;">
    <a class="btn btn-outline-info btn-lg" href="{% url 'paintings' %}" role="button">Continue Shoppping</a>
    <a class="btn btn-outline-danger btn-lg ml-3" href="{% url 'logout' %}" role="button">Logout</a>
</div>
{% endblock %}

templates/main/user-profile.html
{% extends 'main/layouts/base.html' %}

{% load static %}

{% block content %}
<div>
    <h3>{{ artist.id }}</h3>
    <h3>{{ artist.profile.first_name }}</h3>
    <h3>{{ artist.profile.last_name }}</h3>
    <h3>{{ artist.profile.contact }}</h3>
    <h3>{{ artist.profile.email }}</h3>
    <h3>{{ artist.medium }}</h3>
    <h3>{{ artist.style }}</h3>
    <h3>{{ artist.workEx }}</h3>
    <a href="{% url 'add-painting' artist.id %}"><h3>ADD PAINTING</h3></a>
    <h3><img src="{{ artist.photo }}" alt=""></h3>
        {% for painting in artist.painting_set.all %}
            <img src="{{ painting.photo }}" class="card-img-top">
        {% endfor %}
    </div>
</div>
{% endblock %}